version: '3'

services:
  db:
    image: postgres:latest
    restart: always
    environment:
      POSTGRES_DB: alnur
      POSTGRES_USER: alnur
      POSTGRES_PASSWORD: alnur
    ports:
      - "5432:5432"
